### ISSUE TITLE
[REQUEST] New place names

### ISSUE THREAD

**Issue by Good9tTo9t** [mbahArip/japanLicensePlate_Generator#2]
Place names added after 2020/5 are missing. If you cannot update it, can you share the font that you used so I can update it on my fork? I don't know much about japanese administrative divisions, so I'm not super confident in doing it all by myself.

List of missing place names. 
- 苫小牧
- 知床（釧路、北見市）
- 弘前
- 白河
- 市川
- 船橋
- 市原
- 松戸
- 板橋
- 江東
- 葛飾
- 上越
- 四日市
- 伊勢志摩
- 飛鳥
- 出雲
- 高松

**Comment by mbahArip** [comment]
Hello, I don't think I'll update it (at least in the near future)* since I'm still focusing on another project.

It's been a long time, and I'm not 100% sure
but I think it's MS UI Gothic with character adjustment + stroke (3px if you're following the characters settings below)
![image](https://github.com/mbahArip/japanLicensePlate_Generator/assets/62494292/7c2bb01c-deaa-488e-83e5-8504ebe95de3)
![image](https://github.com/mbahArip/japanLicensePlate_Generator/assets/62494292/211556ae-804a-4bb4-9402-0bafc7c379c1)

It's probably better to search some plate sample / photograph and trace it
since all my texture isn't accurate

---

*I'm actually tried to update it couple weeks back and make it easier to extend the generator for another country plate
But I kinda stuck with the generator (and also the texture, since I don't actually want to use an inaccurate texture), and the project got postponed (or probably going to drop it)

**Comment by Good9tTo9t** [comment]
Well, I just added them to my fork with a similar font. I know they aren't 100% accurate but it's a great tool nontheless.
